name: Jina Hub Image Builder
description: Build & test your Pod into Docker image and share with the community
author: Jina AI

outputs:
  success_targets:
    description: Successfully built targets with their paths
  failed_targets:
    description: Failed built targets with their paths
inputs:
  push:
    description: 'if add --push to jina hub build command'
    required: false
    default: 'False'
  dockerhub_username:
    description: 'user name of the Docker registry'
    required: false
  dockerhub_password:
    description: 'the plaintext password of the docker hub'
    required: false
  dockerhub_registry:
    description: 'the URL to the Docker registry'
    required: false
    default: 'https://index.docker.io/v1/'
  slack_webhook:
    description: 'webhook for Slack notification'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.push }}
    - ${{ inputs.dockerhub_username }}
    - ${{ inputs.dockerhub_password }}
    - ${{ inputs.dockerhub_registry }}
    - ${{ inputs.slack_webhook }}
branding:
  icon: 'package'
  color: 'green'
